# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://chamboin.github.io
date_format: "ordinal"
title: 达瓦里希
subtitle: "达瓦里希，为了最高理想"
description: "又一个普通博客"
keywords: 学习, Chamboin Zhang
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Chamboin Zhang
organization: 
organization_url: 
github_username: chamboin
location: Changsha, China
email: ichamboin@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chamboin/chamboin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: chamboin
    repo: blog-comment
    oauth:
        client_id: 2611d32ef01625630479
        client_secret: 30f57e22138e5a2ebf012e6693d301bc18a34371
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: chamboin
    repo: blog-comment
    clientID: 2611d32ef01625630479
    clientSecret: 30f57e22138e5a2ebf012e6693d301bc18a34371
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 
